# CHANGEME: Set these variable to your liking
title: Crested Gecko Habitat Control Center
description: ESPHome firmware for KC868-A16 – temperature, humidity, lighting, misting & feeding management for crested geckos
theme: jekyll-theme-slate
