# CHANGEME: Set these variable to your liking
title: KC868-A16 OI-6950 Modbus Bridge
description: ESP32-based Modbus RTU bridge for OI-6950 gas monitors – powered by ESPHome
theme: jekyll-theme-slate
